name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # runs daily at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-snake
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            profile-snake/github-snake.svg
            profile-snake/github-snake-dark.svg?palette=github-dark
      - name: Commit and Push Snake
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add profile-snake/
          if git commit -m "generated"; then
            git push
          fi
