name: Update README Timestamp

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every 30 minutes
  workflow_dispatch:      # Allows manual trigger

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Update timestamps
        run: |
          # Get current UTC datetime
          CURRENT_DATETIME=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          CURRENT_DATE=$(date -u +"%Y-%m-%d")
          BADGE_DATE=$(date -u +"%Y--%m--%d_%H%%3A%M%%3A%S_UTC")
          
          # Update the badge timestamp (using proper formatting)
          sed -i "s/Updated-[0-9-]*_[0-9:]*_UTC/Updated-$BADGE_DATE/" README.md
          
          # Update the footer timestamp
          sed -i "s/Last Updated: .*UTC/Last Updated: $CURRENT_DATETIME/" README.md
          
          # Update the header current date and time
          sed -i "s/Current Date and Time (UTC): .*/Current Date and Time (UTC): $CURRENT_DATETIME/" README.md

      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update timestamps: $(date -u)" && git push)