name: Update Featured Projects

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight UTC
  workflow_dispatch:
    inputs:
      username:
        description: "GitHub username (overrides auto-detect)"
        required: false
        default: ""
      top:
        description: "Number of top repos to include"
        required: false
        default: "6"
      exclude:
        description: "Comma-separated list of repo names to exclude (overrides EXCLUDE_REPOS env)"
        required: false
        default: "YoutubeSourceCodes,VueXpressPro-Backend,VueXpressPro-Frontend,LoveDoLove"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # prefer workflow input username if provided, otherwise let the script detect from GITHUB_REPOSITORY
          if [ "${{ github.event.inputs.username }}" != "" ]; then
            USER_ARG="--user '${{ github.event.inputs.username }}'"
          else
            USER_ARG=""
          fi
          TOP_ARG="--top ${{ github.event.inputs.top || '6' }}"
          # if the workflow 'exclude' input is provided, export it so the Python script picks it up from env
          if [ "${{ github.event.inputs.exclude }}" != "" ]; then
            export EXCLUDE_REPOS="${{ github.event.inputs.exclude }}"
            echo "[INFO] EXCLUDE_REPOS set from workflow input: $EXCLUDE_REPOS"
          fi
          python scripts/update_featured_projects.py $USER_ARG --file portfolio-website/public/index.html $TOP_ARG

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update featured projects (automated)"
          branch: main
          file_pattern: |
            portfolio-website/public/index.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
